import json
from typing import Dict, Any

class ReportGenerator:
    """Generates structured Markdown and JSON risk registers for AI audits."""

    def generate_markdown_report(self, nist_res: dict, atlas_res: dict, eu_res: dict) -> str:
        report = f"""# Enterprise AI Risk & Governance Audit Report
Generated by **AI Risk Auditor** (`pietrodiwalsi-design/ai-risk-auditor`)

## 1. Executive Summary
- **EU AI Act Classification:** {eu_res.get('risk_tier', 'Unknown')}
- **NIST AI RMF 1.0 Overall Score:** {nist_res.get('overall_score', 0)}% ({nist_res.get('compliance_tier', 'N/A')})
- **MITRE ATLAS Security Status:** {atlas_res.get('status', 'Unknown')}

## 2. NIST AI RMF Breakdown
{json.dumps(nist_res.get('function_breakdown', {}), indent=2)}

## 3. Mandatory Regulatory Obligations
"""
        for ob in eu_res.get("mandatory_obligations", []):
            report += f"- [ ] {ob}\n"
        return report
